# Generated by Django 6.0.4 on 2026-05-05 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_monitorlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('user', 'url')},
        ),
    ]
