# Generated by Django 6.0.4 on 2026-05-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_incident_incidentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='slow_alert_threshold',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DOWN', 'DOWN'), ('SLOW', 'SLOW'), ('RECOVERY', 'RECOVERY'), ('SSL', 'SSL')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('message', models.TextField()),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitor.incident')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.website')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
