# Generated by Django 6.0.4 on 2026-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='monitor_not_user_id_23f2f4_idx',
            old_name='monitor_noti_user_id_72cf32_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='monitor_not_user_id_fa9e13_idx',
            old_name='monitor_noti_user_id_3548e1_idx',
        ),
    ]
