# Generated by Django 5.0.4 on 2026-05-11 10:52

import django.db.models.deletion
import monitor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_rename_monitor_noti_user_id_72cf32_idx_monitor_not_user_id_23f2f4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=monitor.models.uploaded_log_file_path)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParsedError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=120)),
                ('raw_line', models.TextField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen_line', models.PositiveIntegerField()),
                ('uploaded_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_errors', to='monitor.uploadedlog')),
            ],
            options={
                'ordering': ['-count', 'first_seen_line', 'id'],
            },
        ),
    ]
