# Generated by Django 5.0.4 on 2026-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_uploadedlog_parsederror'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsederror',
            name='category',
            field=models.CharField(choices=[('database', 'Database'), ('authentication', 'Authentication'), ('timeout', 'Timeout'), ('http', 'HTTP'), ('network', 'Network'), ('django', 'Django'), ('frontend', 'Frontend'), ('security', 'Security'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='parsederror',
            name='last_seen_line',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parsederror',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=16),
        ),
    ]
