# Generated by Django 5.0.4 on 2026-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_force_uploadedlog_file_analyzer_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
